[0m11:26:31.821719 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d0c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11071eaa0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11071e380>]}


============================== 11:26:31.824276 | 10253037-a5fb-4320-bf49-e77293a81833 ==============================
[0m11:26:31.824276 [info ] [MainThread]: Running with dbt=1.9.4
[0m11:26:31.824604 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'version_check': 'True', 'profiles_dir': '/Users/ayomideabass/.dbt', 'log_path': 'logs', 'debug': 'False', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'False', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'invocation_command': 'dbt build --target dev', 'introspect': 'True', 'target_path': 'None', 'log_format': 'default', 'send_anonymous_usage_stats': 'True'}
[0m11:26:31.824931 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/ayomideabass/Documents/Projects/football_stats_project/dbt/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m11:26:31.830538 [debug] [MainThread]: Resource report: {"command_name": "build", "command_success": false, "command_wall_clock_time": 0.04092554, "process_in_blocks": "0", "process_kernel_time": 0.101065, "process_mem_max_rss": "112443392", "process_out_blocks": "0", "process_user_time": 0.611075}
[0m11:26:31.830846 [debug] [MainThread]: Command `dbt build` failed at 11:26:31.830778 after 0.04 seconds
[0m11:26:31.831031 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x106d0c730>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11071d9f0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11071ea40>]}
[0m11:26:31.831209 [debug] [MainThread]: Flushing usage events
[0m11:26:32.203878 [debug] [MainThread]: An error was encountered while trying to flush usage events
